// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddAnotationInCustomerCls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAnotationInCustomerCls));
        
        string IMigrationMetadata.Id
        {
            get { return "201609181719111_AddAnotationInCustomerCls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
